backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "images/user_uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "themes" # Used in routes, e.g., /admin/collections/blog
    label: "Themes" # Used in the UI
    folder: "_themes/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "product"
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description_markdown", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Github", name: "github", widget: "string"}
      - {label: "Download URL", name: "download", widget: "string"}
      - {label: "Support URL", name: "support", widget: "string"}
      - {label: "Demo URL", name: "demo", widget: "string", default: "https://rawcdn.githack.com/USER/REPO/master/"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Tags (Seperated by comma ',')", name: "style", widget: "string"}
      - {label: "Style (dark/light)", name: "style", widget: "string", default: "dark"}
      - {label: "Publish Date", name: "date", widget: "datetime"}